const SIGN_IN = 'SIGN_IN';
const SIGN_UP = 'SIGN_UP';
const AUTO_SIGN_IN = 'AUTO_SIGN_IN';
const GET_NEWS = 'GET_NEWS';
const GET_GAMES = 'GET_GAMES';

// EXPORTING ALL
export {
  SIGN_IN,
  SIGN_UP,
  AUTO_SIGN_IN,
  GET_NEWS,
  GET_GAMES
} 